# Generated by Django 4.2.6 on 2023-10-26 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qtd_books', models.IntegerField()),
                ('qtd_pages', models.IntegerField()),
                ('cover', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=255)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.genders')),
            ],
        ),
    ]
