# Generated by Django 4.2.7 on 2023-11-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_books_qtd_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='qtd_pages',
            field=models.IntegerField(default=0),
        ),
    ]
