# Generated by Django 4.2.7 on 2023-11-25 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_rentedbooks_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedbooks',
            name='date',
        ),
        migrations.AddField(
            model_name='rentedbooks',
            name='datea',
            field=models.DateField(default=datetime.datetime(2023, 11, 25, 17, 26, 34, 671682)),
        ),
    ]
