# Generated by Django 4.2.7 on 2023-11-25 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_remove_rentedbooks_datea_rentedbooks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedbooks',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
