# Generated by Django 4.2.7 on 2023-11-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_alter_rentedbooks_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedbooks',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
